local wezterm = require "wezterm"
---------------------------------------------------------------
return {
  term = "wezterm",
  font_size = 16,
  color_scheme_dirs = { os.getenv "HOME" .. "/.config/wezterm/colors/" },
  color_scheme = "Catppuccin Mocha",
  font = wezterm.font { family = "JetBrainsMono Nerd Font Mono" },
  window_padding = {
    left = 12,
    right = 12,
    top = 12,
    bottom = 12,
  },
  check_for_updates = true,
  use_dead_keys = false,
  warn_about_missing_glyphs = false,
  window_decorations = "RESIZE",
  window_background_opacity = 1.00,
  animation_fps = 1,
  cursor_blink_ease_in = "Constant",
  cursor_blink_ease_out = "Constant",
  cursor_blink_rate = 0,
  force_reverse_video_cursor = false,
  hide_tab_bar_if_only_one_tab = true,
  adjust_window_size_when_changing_font_size = false,
  selection_word_boundary = " \t\n{}[]()\"'`,;:│=&!%",
  use_resize_increments = true,
  use_fancy_tab_bar = false,
  exit_behavior = "CloseOnCleanExit",
  tab_bar_at_bottom = true,
  window_close_confirmation = "AlwaysPrompt",
  skip_close_confirmation_for_processes_named = {
    "bash",
    "sh",
    "zsh",
    "fish",
    "tmux",
  },
  leader = { key = " ", mods = "CTRL" },
  keys = {
    -- tmux
    { key = "|", mods = "LEADER", action = wezterm.action.SplitHorizontal { domain = "CurrentPaneDomain" } },
    { key = "\\", mods = "LEADER", action = wezterm.action.SplitVertical { domain = "CurrentPaneDomain" } },
    { key = "c", mods = "LEADER", action = wezterm.action.SpawnTab "CurrentPaneDomain" },
    { key = "m", mods = "LEADER", action = wezterm.action.TogglePaneZoomState },
    { key = "h", mods = "LEADER", action = wezterm.action.ActivatePaneDirection "Left" },
    { key = "j", mods = "LEADER", action = wezterm.action.ActivatePaneDirection "Down" },
    { key = "k", mods = "LEADER", action = wezterm.action.ActivatePaneDirection "Up" },
    { key = "l", mods = "LEADER", action = wezterm.action.ActivatePaneDirection "Right" },
    { key = "n", mods = "LEADER", action = wezterm.action.ActivateTabRelative(1) },
    { key = "p", mods = "LEADER", action = wezterm.action.ActivateTabRelative(-1) },
    { key = "x", mods = "LEADER", action = wezterm.action.CloseCurrentPane { confirm = true } },
    {
      key = ",",
      mods = "LEADER",
      action = wezterm.action.PromptInputLine {
        description = "Tab name",
        action = wezterm.action_callback(function(window, _, line)
          if line then window:active_tab():set_title(line) end
        end),
      },
    },
    -- allow tmux to receive special bindings
    { key = "'", mods = "CTRL", action = wezterm.action.SendString "\x1b[27;5;39~" },
    { key = ";", mods = "CTRL", action = wezterm.action.SendString "\x1b[27;5;59~" },
    { key = ",", mods = "CTRL", action = wezterm.action.SendString "\x1b[27;5;44~" },
    { key = "-", mods = "CTRL", action = wezterm.action.SendString "\x1b[27;5;45~" },
    { key = "=", mods = "CTRL", action = wezterm.action.SendString "\x1b[27;5;61~" },
    { key = "Enter", mods = "SHIFT", action = wezterm.action.SendString "\x1b[13;2u~" },
    { key = "Enter", mods = "CTRL", action = wezterm.action.SendString "\x1b[13;5u~" },
  },
}
