#!/usr/bin/env sh

# Configure sripting addition (https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition)
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# Global settings
yabai -m config                            \
  layout                      bsp          \
  window_placement            second_child \
  top_padding                 12           \
  bottom_padding              12           \
  left_padding                12           \
  right_padding               12           \
  window_gap                  12           \
  window_border               on           \
  window_border_width         4            \
  window_border_blur          off          \
  active_window_border_color  0xFFC4A6F5   \
  normal_window_border_color  0x002E3440   \
  insert_feedback_color       0xff7793d1   \
  window_opacity              off          \
  active_window_opacity       1.0          \
  normal_window_opacity       0.9          \
  window_opacity_duration     0.15         \
  window_animation_duration   0.0          \
  mouse_follows_focus         off          \
  mouse_modifier              fn           \
  mouse_action1               move         \
  mouse_action2               resize       \
  mouse_drop_action           swap

# Space labels
yabai -m space 2 --label "Code"
yabai -m space 3 --label "Productivity"
yabai -m space 4 --label "Social"
yabai -m space 5 --label "Media"
yabai -m space 6 --label "Misc"

# Code
yabai -m rule --add app="^iTerm$" space="Code"
yabai -m rule --add app="^Alacritty$" space="Code"
yabai -m rule --add app="^WezTerm$" space="Code"
yabai -m rule --add app="^kitty$" space="Code"

# Productivity
yabai -m rule --add app="^(Microsoft (OneNote|Teams|Word|PowerPoint|Excel))$" space="Productivity"
yabai -m rule --add app="^Obsidian$" space="Productivity"

# Social
yabai -m rule --add app="^Discord$" space="Social"
yabai -m rule --add app="^Mail$" space="Social"
yabai -m rule --add app="^Microsoft Outlook$" space="Social"

# Media
yabai -m rule --add app="^Spotify$" space="Media"
yabai -m rule --add app="^Music$" space="Media"
yabai -m rule --add app="^Podcasts$" space="Media"

# Misc
yabai -m rule --add app="^Calendar$" space="Misc"

# Apps to not manage (ignore)
yabai -m rule --add label="Finder" app="^Finder$" title="^(Co(py|nnect)|Move|Info|Pref|Finder Settings|Go to Folder)$" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advanced)$" manage=off
yabai -m rule --add label="Calendar" app="^Calendar$" title="^(General|(Account|Alert)s|Advanced)$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="^System Information$" manage=off
yabai -m rule --add label="Mail" app="^Mail$" title="^(General|(Account|Fonts & Color|Signature|Reule|Extension)s|Junk Mail|Viewing|Composing|Privacy)$" manage=off
yabai -m rule --add label="Orion" app="^Orion$" title="^(General|Appearance|Browsing|Sync|Passwords|Privacy|Search|Websites|Advanced)$" manage=off
yabai -m rule --add label="Discord Updater" app="^Discord$" title="Discord Updater" manage=off
yabai -m rule --add label="Microsoft Teams" app="^Microsoft Teams$" title="Loading Microsoft Teams" manage=off
yabai -m rule --add label="Books" app="^Books$" title="^(General|Reading|Playback|Advanced)$" manage=off
yabai -m rule --add label="1Password Settings" app="^1Password$" title="Settings" manage=off
yabai -m rule --add label="Arc Settings" app="^Arc$" title="^(Joshua|General|Shortcuts|Little Arc|Advanced)$" manage=off
yabai -m rule --add label="Arc PiP" app="^Arc$" title="^$" mouse_follows_focus=off
yabai -m rule --add label="Little Arc" app="^Arc$" title="^Space 1$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Dictionary$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Simulator$" manage=off
yabai -m rule --add app="^Installer$" manage=off
yabai -m rule --add app="^Digital Color Meter$" manage=off
yabai -m rule --add app="^Gifski$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^QuickTime Player$" manage=off
yabai -m rule --add app="^Photo Booth$" manage=off
yabai -m rule --add app="^JetBrains Toolbox$" manage=off
yabai -m rule --add app="^LinearMouse$" manage=off

# Make all non-resizeable windows float (#1317)
# yabai -m signal --add event=window_created action='yabai -m query --windows --window $YABAI_WINDOW_ID | jq -er ".\"can-resize\" or .\"is-floating\"" || yabai -m window $YABAI_WINDOW_ID --toggle float'
