gui:
  nerdFontsVersion: 3
promptToReturnFromSubprocess: false
customCommands:
  - key: "<c-g>"
    description: "Open GitHub Pull Request"
    command: "gh pr create --fill --web"
    context: "global"
    loadingText: "Creating pull request on GitHub"
  - key: "M"
    description: "Open file in git mergetool"
    command: "git mergetool {{ .SelectedFile.Name }}"
    context: "files"
    loadingText: "Opening git mergetool"
    subprocess: true
